### ISSUE TITLE
Graph constructor exited with an error?

### ISSUE THREAD

**Issue by suadsuljic7** [GreenWaves-Technologies/occupancy_management#16]
Hi,
I download and build the latest gap_sdk, installed the toolchain, board is gapoc b_2.4, and build the gap8_project_v2 example.
I run the example with "make run" and this is the output:

0
GAP8 INIT TARGET
GAP8 examine target
Init jtag
Initialising GAP8 JTAG TAP
Loading binary through JTAG

	 *** Therm Eye ***

	   HYPER Version

Entering main controller
Loading Image from File
Image ../../../samples/im2.pgm, [W: 80, H: 80], Gray, Size: 6400 bytes, Loaded sucessfully
Init NN
Allocating Buffers in L3
Constructor
Graph constructor exited with an error
Traceback (most recent call last):
  File "/home/suad/gap/gap_sdk/utils/gapy/gapy", line 162, in <module>
    main()
  File "/home/suad/gap/gap_sdk/utils/gapy/gapy", line 152, in main
    operationFunc(args, config, system)
  File "/home/suad/gap/gap_sdk/utils/gapy/run.py", line 189, in operationFunc
    raise RuntimeError('Runner has failed with value: %d' % status)
RuntimeError: Runner has failed with value: -1
make: *** [/home/suad/gap/gap_sdk/utils/rules/pulp_rules.mk:258: run] Error 1

**Comment by Yaooooo** [comment]
Hi,

Could you please provide more information about the board?
It's a OSPI RAM/FLASH version? or HyperRAM/HyperFlash version?
And which config you are using for preparing your environment? 

If you don't know the detail, could you please provide a photo of your board?

Thanks,
